name: prs

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install deps
        run: npm install
      - name: build client
        run: npm run build
      - name: build server
        run: npm run build-server

